apiVersion: v1
kind: Pod
metadata:
  name: os-ubuntu
  namespace: demo
spec:
  containers:
  - name: os-ubuntu
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "3d"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "10m"
      limits:
        memory: "512Mi"
        cpu: "100m"